university:
  - ref: 'Author'
    org: 'R Certificate Feasibility Report'
    loc: 'Masters in Analytics Program'
    beg: false
    end: 2012
    key: '2012A'
    url: 'https://sites.google.com/a/cs.usfca.edu/r-certification/'

  - ref: 'Participant'
    org: 'Data Science Undergraduate Program Proposal'
    loc: 'College of Arts and Sciences'
    beg: false
    end: 2012
    key: '2012B'
    url: false

  - ref: 'Organizer'
    org: 'CS Night Game Jam'
    loc: 'Department of Computer Science'
    beg: 2012
    end: 2013
    key: '2013A'
    url: 'http://tutoringcenter.cs.usfca.edu/gamejam/'

  - ref: 'Organizer'
    org: 'Student Data Visualization Contest'
    loc: 'Department of Computer Science'
    beg: false
    end: 2013
    key: '2013B'
    url: 'https://sites.google.com/a/cs.usfca.edu/datavis/contest'

  - ref: 'Co-Author'
    org: 'MSCS Program Revision Proposal'
    loc: 'MS in Computer Science Program'
    beg: 2013
    end: 2014
    key: '2014A'
    url: false

  - ref: 'Faculty Sponsor'
    org: 'CS Tutoring Center'
    loc: 'Department of Computer Science'
    beg: 2013
    end: 2014
    key: '2014B'
    url: 'https://tutoringcenter.cs.usfca.edu/'

  - ref: 'Committee Member'
    org: 'Tenure-Track Faculty Search'
    loc: 'Department of Mathematics'
    beg: 2013
    end: 2014
    key: '2014C'
    url: false

  - ref: 'Open Classroom Host'
    org: 'Educational Technology Focus'
    loc: 'Center for Teaching Excellence'
    beg: false
    end: 2014-03-19
    key: '2014D'
    url: 'https://usfcte.net/activities/openclassrooms/hosts/'

  - ref: 'Committee Member'
    org: 'Term Faculty Search'
    loc: 'MS in Analytics Program'
    beg: false
    end: 2015
    key: '2015A'
    url: false

  - ref: 'Participant'
    org: 'TechConnect Initiative'
    loc: 'College of Arts and Sciences'
    beg: false
    end: 2015
    key: '2015B'
    url: false

  - ref: 'Panel Moderator'
    org: "Steppin' Up in STEM: Women in Technology &amp; Education"
    loc: 'Career Services Center'
    beg: false
    end: 2015-11-03
    key: '2015C'
    url: false

  - ref: 'Committee Member'
    org: 'Term Faculty Search'
    loc: 'Department of Computer Science'
    beg: false
    end: 2015
    key: '2015D'
    url: false

  - ref: 'Co-Organizer'
    org: 'Data Visualization Speaker Series'
    loc: 'College of Arts and Sciences'
    beg: 2013
    end: 2016
    key: '2016A'
    url: 'https://vgl.cs.usfca.edu/dvss/'

  - ref: 'Graduate Advisor'
    org: 'MS in Computer Science Program'
    loc: 'College of Arts and Sciences'
    beg: 2013
    end: 2016
    key: '2016B'
    url: false

  - ref: 'Graduate Director'
    org: 'MS in Computer Science Program'
    loc: 'College of Arts and Sciences'
    beg: 2013
    end: 2016
    key: '2016C'
    url: false

  - ref: 'Committee Member'
    org: 'Tenure-Track Faculty Search'
    loc: 'Department of Computer Science'
    beg: 2015
    end: 2016
    key: '2016D'
    url: false

  - ref: 'Invited Presenter'
    org: '"Innovative Uses of Technology in CS," CIT Tech Intensives Program, Center for Instruction and Technology'
    loc: 'University of San Francisco'
    beg: false
    end: 2016-03-07
    key: '2016E'
    url: false

  - ref: 'Committee Member'
    org: 'Tenure-Track Faculty Search'
    loc: 'Department of Computer Science'
    beg: 2016
    end: 2017
    key: '2016F'
    url: false

  - ref: 'Committee Member'
    org: 'Tenure-Track Faculty Search'
    loc: 'Department of Computer Science'
    beg: 2018
    end: 2019
    key: '2018F'
    url: false

  - ref: 'Committee Chair'
    org: 'Newmark Women in Tech Scholarships'
    loc: 'College of Arts and Sciences'
    beg: 2019
    end: 2020
    key: '2019B'
    url: false

  - ref: 'Committee Member'
    org: 'Tenure-Track Faculty Search'
    loc: 'Department of Psychology'
    beg: 2019
    end: 2020
    key: '2019C'
    url: false

  - ref: 'Invited Co-Presenter'
    org: '"Facilitating Communication and Collaboration in Your Course
    using Free Online Tools: Canvas Discussion Boards and Piazza," Peer2Peer Series on Teaching &amp; Technology, Instructional Technology and Training'
    loc: 'University of San Francisco'
    beg: false
    end: 2019-03-26
    key: '2019A'
    url: 'https://usfcte.net/peer2peer/'

  - ref: 'Open Classroom Host'
    org: 'Educational Technology Focus'
    loc: 'Center for Teaching Excellence'
    beg: false
    end: 2020-02-12
    key: '2020A'
    url: 'http://usfcte.net/openclassrooms/'

  - ref: 'Co-Organizer and Instructor'
    org: 'CS Head Start Week'
    loc: 'Department of Computer Science'
    beg: false
    end: 2019-08-16
    key: '2019D'
    url: 'https://scholars.cs.usfca.edu/start2019/'

  - ref: 'Co-Organizer and Instructor'
    org: 'CS Head Start Week'
    loc: 'Department of Computer Science'
    beg: false
    end: 2020-08-11
    key: '2020A'
    url: 'https://scholars.cs.usfca.edu/start2020/'

  - ref: 'Committee Member and Mentor'
    org: 'Clare Booth Luce Scholarships'
    loc: 'College of Arts and Sciences'
    beg: 2018
    end: 2020
    key: '2018G'
    url: 'https://www.hluce.org/programs/clare-boothe-luce-program/'

  - ref: 'Co-Founder'
    org: 'Visualization and Graphics Lab'
    loc: 'Department of Computer Science'
    beg: 2015
    end: 'Now'
    key: 'Now-2015'
    url: 'https://vgl.cs.usfca.edu/'

  - ref: 'Co-Chair'
    org: 'Tenure-Track Faculty Search'
    loc: 'Department of Computer Science'
    beg: 2021
    end: 2022
    key: '2021A'
    url: false

  - ref: 'Webtrack Advisor'
    org: 'CS Major'
    loc: 'Department of Computer Science'
    beg: false
    end: 2019
    key: '2019E'
    url: false

  - ref: 'Webtrack Advisor'
    org: 'CS Major'
    loc: 'Department of Computer Science'
    beg: false
    end: 2020
    key: '2020C'
    url: false

  - ref: 'Co-Chair'
    org: 'Hybrid Learning Task Force'
    loc: 'Department of Computer Science'
    beg: false
    end: 2022
    key: '2022A'
    url: false

  - ref: 'Co-Organizer'
    org: 'Computer Science Undergraduate Curriculum Retreat'
    loc: 'Department of Computer Science'
    beg: false
    end: 2022-12-16
    key: '2022B'
    url: false

  - ref: 'Co-Author'
    org: 'Computer Science Bylaws'
    loc: 'Department of Computer Science'
    beg: 2022
    end: 2023
    key: '2023-2022'
    url: false

  - ref: 'Committee Member'
    org: 'Tenure-Track Faculty Search'
    loc: 'MS in Data Science Program'
    beg: 2022
    end: 2023
    key: '2023-2022'
    url: false

  - ref: 'Guest Speaker'
    org: 'Faculty Speaker Series + Dons Talk, ACM Student Chapter, Department of Computer Science'
    beg: false
    end: 2023-09-14
    key: '20230914'

  - ref: 'Panelist'
    org: '"How My Identity Shaped My Career in STEM," Diversity in STEM Council, College of Arts and Sciences'
    beg: false
    end: 2025-02-13
    key: '20250213'

  # - ref: 'Moderator'
  #   org: '"Obstacles and Failures," Faculty Discussion, CS 286 Peer-Led Seminar in Tech, Department of Computer Science'
  #   beg: false
  #   end: 2025-02-14
  #   key: '20250214'

  - ref: 'Guest Speaker'
    org: '"Imposter Syndrome Workshop," Women in Tech Student Group, Department of Computer Science'
    beg: false
    end: 2025-03-20
    key: '20250320'

  - ref: 'Co-Organizer'
    org: 'Moment to Movement: Evolving & Sustaining Anti-Racist Pedagogy'
    loc: 'College of Arts and Sciences'
    beg: 2022
    end: 'Now'
    key: 'Now-2022B'
    url: false

  - ref: 'Advisor'
    org: 'CS Major and Minor'
    loc: 'Department of Computer Science'
    beg: 2017
    end: 'Now'
    key: 'Now-2017'
    url: false

  - ref: 'Co-Investigator, Scholar Coordinator, Faculty Mentor'
    org: 'Community Engaged Scholars in Computer Science'
    loc: 'Department of Computer Science'
    beg: 2019
    end: '2025'
    key: '2025-2019'
    url: 'https://scholars.cs.usfca.edu/'

professional:
  - ref: 'Program Committee'
    org: 'Center of Academic Excellence (CAE) Workshop on Insider Threat (WIT)'
    loc: 'St. Louis, Missouri'
    beg: false
    end: 2010-11-14
    key: '201011'
    url: false

  - ref: 'Paper Reviewer'
    org: 'Workshop on Cyber Security Experimentation and Test (CSET)'
    loc: 'San Francisco, California'
    beg: 2011-08-08
    end: 2011-08-12
    key: '201108'
    url: 'https://www.usenix.org/legacy/event/cset11/index.html'

  - ref: 'Local Chair'
    org: 'New Security Paradigms Workshop (NSPW)'
    loc: 'Marin County, California'
    beg: 2011-09-12
    end: 2011-09-15
    key: '201109'
    url: 'https://www.nspw.org/2011'

  - ref: 'Program Committee'
    org: 'International Conference on Computers and Their Applications (CATA)'
    loc: 'Las Vegas, Nevada'
    beg: 2012-03-12
    end: 2012-03-14
    key: '201203'
    # url: 'http://web.mst.edu/~cata2012/Archive/'

  - ref: 'Poster Chair'
    org: 'IEEE Symposium on Security and Privacy (IEEE S&amp;P)'
    loc: 'San Francisco, California'
    beg: 2013-05-19
    end: 2013-05-22
    key: '201305'
    url: 'https://www.ieee-security.org/TC/SP2013/'

  - ref: 'Publication and Publicity Chair'
    org: 'Workshop on Visualization for Cyber Security (VizSec)'
    loc: 'Atlanta, Georgia'
    beg: false
    end: 2013-10-14
    key: '201310'
    url: 'https://vizsec.org/vizsec2013/'

  - ref: 'Proposal Review Panelist'
    org: 'NSF Secure and Trustworthy Cyberspace (SaTC)'
    loc: 'Arlington, Virginia'
    beg: false
    end: 2013
    key: '201312'
    url: 'https://www.nsf.gov/pubs/2013/nsf13578/nsf13578.htm'

  - ref: 'Poster Chair'
    org: 'IEEE Symposium on Security and Privacy (IEEE S&amp;P)'
    loc: 'San Jose, California'
    beg: 2014-05-18
    end: 2014-05-21
    key: '201405'
    url: 'https://www.ieee-security.org/TC/SP2014/'

  - ref: 'Program Committee, Security/Privacy Track'
    org: 'Grace Hopper Celebration of Women in Computing (GHC)'
    loc: 'Phoenix, Arizona'
    beg: 2014-10-08
    end: 2014-10-10
    key: '201410'
    url: 'https://ghc.anitab.org/wp-content/uploads/sites/2/2014/10/ABI_GHC-2014-Online-Program_Addendum.pdf'

  - ref: 'Program Chair'
    org: 'Workshop on Visualization for Cyber Security (VizSec)'
    loc: 'Paris, France'
    beg: false
    end: 2014-11-10
    key: '201411'
    url: 'https://vizsec.org/vizsec2014/'

  - ref: 'Program Committee'
    org: 'Cyber and Information Security Research (CISR) Conference'
    loc: 'Oak Ridge, Tennessee'
    beg: 2015-04-07
    end: 2015-04-09
    key: '201504'
    # url: 'http://www.cisr.ornl.gov/cisrc15/'

  - ref: 'Co-Publication and Poster Chair'
    org: 'IEEE Symposium on Security and Privacy (IEEE S&amp;P)'
    loc: 'San Jose, California'
    beg: 2015-05-18
    end: 2015-05-20
    key: '201505'
    url: 'https://www.ieee-security.org/TC/SP2015/'

  - ref: 'Publication Chair'
    org: 'Symposium on Visualization for Cyber Security (VizSec)'
    loc: 'Chicago, Illinois'
    beg: false
    end: 2015-10-26
    key: '201510'
    url: false

  - ref: 'Short Papers Reviewer'
    org: 'EG/VGTC Conference on Visualization (EuroVis)'
    loc: 'Groningen, Netherlands'
    beg: 2016-06-06
    end: 2016-06-10
    key: '201606'
    # url: 'http://www.cs.rug.nl/jbi/eurovis2016/'

  - ref: 'Publication Chair'
    org: 'Symposium on Visualization for Cyber Security (VizSec)'
    loc: 'Baltimore, Maryland'
    beg: false
    end: 2016-10-24
    key: '20161024'
    url: 'https://vizsec.org/'

  - ref: 'Organizing Committee'
    org: 'Pedagogy of Data Visualization Workshop (PDVW)'
    loc: 'Baltimore, Maryland'
    beg: false
    end: 2016-10-23
    key: '20161023'
    url: 'https://vgl.cs.usfca.edu/pdvw/2016/'

  - ref: 'Program Committee (NIER and Tool Tracks)'
    org: 'IEEE Working Conference on Software Visualization (VISSOFT 2017)'
    loc: 'Shanghai, China'
    beg: 2017-09-18
    end: 2017-09-19
    key: '20170918'
    url: 'http://vissoft17.dcc.uchile.cl/'

  - ref: 'Organizing Committee'
    org: 'Pedagogy of Data Visualization Workshop (PDVW)'
    loc: 'Phoenix, Arizona'
    beg: false
    end: 2017-10-01
    key: '20171001'
    url: 'https://vgl.cs.usfca.edu/pdvw/2017/'

  - ref: 'Papers Reviewer'
    org: 'IEEE Information Visualization (InfoVis)'
    loc: 'Phoenix, Arizona'
    beg: false
    end: 2017-10-01
    key: '20171001'
    url: 'http://ieeevis.org/year/2017/welcome'

  - ref: 'General Chair'
    org: 'Symposium on Visualization for Cyber Security (VizSec)'
    loc: 'Phoenix, Arizona'
    beg: false
    end: 2017-10-02
    key: '20171002'
    url: 'https://vizsec.org/vizsec2017/'

  - ref: 'Screening Committee'
    org: 'Fulbright Thai Graduate Scholarship'
    beg: false
    end: 2018-05-01
    key: '20180501'

  - ref: 'Chair at Large'
    org: 'Symposium on Visualization for Cyber Security (VizSec)'
    loc: 'Berlin, Germany'
    beg: false
    end: 2018-10-22
    key: '20181022a'
    url: 'https://vizsec.org/vizsec2018/'

  - ref: 'Steering Committee'
    org: 'Symposium on Visualization for Cyber Security (VizSec)'
    beg: 2018-10-22
    end: 2022-10-17
    key: '20221017'
    url: 'https://vizsec.org/'

  - ref: 'Program Committee'
    org: 'Symposium on Visualization for Cyber Security (VizSec)'
    beg: 2013-10-01
    end: 2022-10-01
    key: '20221001'
    url: 'https://vizsec.org/'

community:
  - ref: 'Guest Speaker'
    org: 'International Book Club discussing "There There" by Tommy Orange'
    beg: false
    end: 2021-07-26
    key: '20210726'

  - ref: 'Guest Speaker'
    org: 'Girl Scouts of the United States of America (GSUSA)'
    beg: false
    end: 2017-04-28
    key: '20170428'

  - ref: 'Guest Speaker, <q>Data Visualizing: Primer and Prospects</q>'
    org: 'Five Keys Schools'
    loc: 'San Francisco County Jail #5, San Bruno, CA'
    beg: false
    end: 2018-03-22
    key: '20180322'
    url: 'https://www.fivekeyscharter.org/'

  - ref: 'Featured as a "Modern Women in Tech" in the "Our Time" Gallery'
    org: 'Grace Hopper Celebration (GHC)'
    beg: false
    end: 2018-09-26
    key: '20180926'
    url: 'https://vimeo.com/289762602/30c246c503'
